### ISSUE TITLE
Two Hikvision DS-2CV2026G0-IDW - can't add second camera

### ISSUE THREAD

**Issue by tgrabows** [toxuin/alarmserver#28]
Hello! 
I love idea with such a simple solution - alarmserver - thank you!

Unfortunately I have problem with "adding" second camera - it always fails.

My config is:
```
hikvision:
  enabled: true              
  cams:
    cam1:                   
      address: 192.168.44.210  
      https: false           
      username: admin 
      password: bothCamHaveSamePass   
      rawTcp: false          
    cam2:                   
      address: 192.168.44.209  
      https: false           
      username: admin        
      password: bothCamHaveSamePass   
      rawTcp: false  
```        
My log looks:
```
Initializing Webhook bus...
WEBHOOK BUS INITIALIZED
STARTED HISILICON SERVER
HIK: Adding camera cam1: http://192.168.44.210/ISAPI/
HIK: USING DIGEST AUTH
HIK: Adding camera cam2: http://192.168.44.209/ISAPI/
HIK: BAD STATUS 401HIK: ERROR: Camera cam2 does not seem to support event streaming
            Is it a doorbell? Try adding rawTcp to its config!
HIK: Closed connection to camera cam2
HIK: USING DIGEST AUTH
HIK: BAD STATUS 401HIK: ERROR: Camera cam2 does not seem to support event streaming
            Is it a doorbell? Try adding rawTcp to its config!
HIK: Closed connection to camera cam2
STARTED HIKVISION SERVER
```

If I swap addresses:
```
hikvision:
  enabled: true              
  cams:
    cam1:                   
      address: 192.168.44.209  
      https: false           
      username: admin 
      password: bothCamHaveSamePass   
      rawTcp: false          
    cam2:                   
      address: 192.168.44.210  
      https: false           
      username: admin        
      password: bothCamHaveSamePass   
      rawTcp: false  
```        

Again problem with second camera:
```
Initializing Webhook bus...
WEBHOOK BUS INITIALIZED
STARTED HISILICON SERVER
HIK: Adding camera cam1: http://192.168.44.209/ISAPI/
HIK: USING DIGEST AUTH
HIK: Adding camera cam2: http://192.168.44.210/ISAPI/
HIK: BAD STATUS 401HIK: ERROR: Camera cam2 does not seem to support event streaming
            Is it a doorbell? Try adding rawTcp to its config!
HIK: Closed connection to camera cam2
HIK: USING DIGEST AUTH
HIK: BAD STATUS 401HIK: ERROR: Camera cam2 does not seem to support event streaming
            Is it a doorbell? Try adding rawTcp to its config!
HIK: Closed connection to camera cam2
STARTED HIKVISION SERVER
```
